version: '3.9'

services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    restart: always
    env_file:
      - .env
    ports:
      - '7000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
